---
title: "Publications"
---

#### 2020

**1.** [**<ins>Li, R.</ins><sup>#</sup>**, Qu, H.<sup>#</sup>, Chen, J., Wang, S., Chater, J.M., Zhang, L., Wei, J., Zhang, Y., Xu, C., Zhong, W.D., Zhu, J., Lu, J., Feng, Y., Chen, W., Ma, R., Ferrante, S.P., Roose, M.L., and Jia, Z., 2020. Inference of Chromosome-length Haplotypes Using Genomic Data of Three or a Few More Single Gametes. **<ins>Molecular Biology and Evolution**</ins>. (IF: 11.062)](https://doi.org/10.1093/molbev/msaa176)  

**2.** [**<ins>Li, R.</ins><sup>#</sup>**, Wang, S.<sup>#</sup>, Cui, Y.<sup>#</sup>, Qu, H., Chater, J.M., Zhang, L., Wei, J., Wang, M., Xu, Y., Yu, L., Lu, J., Feng, Y., Zhou, R., Huang, Y., Ma, R., Zhu, J., Zhong, W., and Jia, Z., 2020. Extended Application of Genomic Selection to Screen Multi-Omics Data for Prognostic Signatures of Prostate Cancer. **<ins>Briefings in Bioinformatics**</ins>. (IF: 8.990)](https://doi.org/10.1093/bib/bbaa197)  

**3.** [Shi, X.<sup>#</sup>, **<ins>Li, R.</ins><sup>#</sup>**, Dong, X., Chen, A.M., Liu, X., Lu, D., Feng, S., Wang, H., and Cai, K., 2020. An Immune-associated gene classifier for lung adenocarcinoma prognosis. **<ins>Journal of Translational Medicine</ins>**. (IF: 4.124)](https://doi.org/10.1186/s12967-020-02233-y)  

**4.** [Gao, X.<sup>#</sup>, Huang, Z.<sup>#</sup>, Guan, C.<sup>#</sup>, Feng, C.<sup>#</sup>, **<ins>Li, R.</ins><sup>#</sup>**, Xie, H.<sup>#</sup>, Que, R., Den, B., Cao, P., Li, M., Lu, J., Huang, Y., Li, M., Yang, W., Yang, X., Wen, C., Liang, X., Yang, Q., Chao, Y., Chan, L., Yenari, A.M., Jin, K.,  Chaudhuri, R.K., Zhang, J., Tan, EK., and Wang, Q., 2020. Multi-modal analysis identifies SVT genes associated with Parkinson's disease. **<ins>Briefings in Bioinformatics**</ins>. (IF: 8.990)](https://academic.oup.com/bib)  

**5.** [Wang, M., **<ins>Li, R.</ins>**, Xu, S., 2020. Deshrinking Ridge Regression for Genome-wide Association Studies. **<ins>Bioinformatics**</ins>. (IF: 5.610)](https://doi.org/10.1093/bioinformatics/btaa345) 

**6.** [Wang, S., Xu, Y., Qu, H., Cui, Y., **<ins>Li, R.</ins>**, Chater J., Yu, Li., Zhou, R., Ma, R., Huang, Y. Qiao, Y., Hu X., Xie, W., Jia, Z., 2020. Boosting Predictabilities of Agronomic Traits in Rice using Bivariate Genomic Selection. **<ins>Briefings in Bioinformatics**</ins>. (IF: 8.990)](https://academic.oup.com/bib/article/doi/10.1093/bib/bbaa103/5867560?guestAccessKey=c06470c6-19c9-48e8-a821-f5eb870eb23b)  

**7.** [Jiao, M., Li, J., Zhang, Q., Xu, Xiu., **<ins>Li, R.</ins>**, Dong, P., Meng, Chun., Li, Y., Wang, L., Qi, W., Kang, K., Wang, H., and Wang, T., 2020. Identification of four potential biomarkers associated with coronary artery disease in non-diabetic patients by Gene Co-expression Network Analysis. **<ins>Frontiers in Genetics**</ins>. (IF: 3.258)](https://www.frontiersin.org/articles/10.3389/fgene.2020.00542/full)  

**8.** [Chater, J., Duong, F., Alas, M., Yip, M., Zib, A., Luu, I., Carrillo-Kashani, A., Wang, S., **<ins>Li, R.</ins>**, Qu, H., Merhaut, D., Jia, Z., 2020. Postharvest Quality of Imported, Domestic and Minimally Processed Pomegranate Fruit. **<ins>International Journal of Fruit Science**</ins>. (IF: 0.877)](https://www.tandfonline.com/doi/full/10.1080/15538362.2020.1734896)  

**9.** [Wang, W., Yuan, D., Su, J., Chen, W., Song, J., Jiang, K., **<ins>Li, R.</ins>**, Qu, H., Yang, S., Hu, B., Zhu, G., Zhang, W., Jiang, F., Zhong, W., Sun, F., Jia, Z., and Zhu, J., 2020. Genome-wide CRISPR-Cas9 Screening in Mice for Identification of Human Genes that Promote Growth and Metastasis of Prostate Cancer. **<ins>Genome Biology**</ins>. (Submitted)](https://clincancerres.aacrjournals.org/)  

**10.** [Huang, C., Rangel, D.S., Qin, X., Bui, C., Bitterli, L., **<ins>Li, R.</ins>**, Jia, Z., Cui, X., and Jin, H., 2020. Epigenetic regulation of plant immune Nod-like receptors through the chromatin remodeling protein BAF60/SWP73. **<ins>Cell Host & Microbe**</ins>. (Submitted)](https://www.cell.com/cell-host-microbe/home) 

**11.** [Feng, Y., Han, Z., Ye, J., Cai, Z., Deng, Y., Liu, R., **<ins>Li, R.</ins>**, Qu, H., Wang, S., Yu, L., Zhou, R., Lu, J., Chater, J.M., Zeng, G., Zhu, J., He, H., Jia, Z., and Zhong, W., 2020. Development of Prognostic Model for Clear Cell Renal Cell Carcinoma Using Biomarkers Selected from Competitive Endogenous RNA Network. **<ins>Cancers**</ins>. (Submitted)](https://www.mdpi.com/journal/cancers)  

**12.** [Ruelas, D., **<ins>Li, R.</ins>**, Franci, V., Lopez, D., Li, L., Min-Oo, G., DI Paolo, J.A., 2020. Abstract: Defining Synovial Signatures in the Rat CIA Model: What Can We Learn About RA Progression?. **<ins>Annuals of the Rheumatic Diseases**</ins>.](https://ard.bmj.com/content/79/Suppl_1/247.2)  


#### 2019

**1.** [Cui, Y.<sup>#</sup>, **<ins>Li, R.</ins><sup>#</sup>**, Li, G.<sup>#</sup>, Zhang, F., Zhu, T., Zhang, Q., Ali, J., Li, Z. and Xu, S., 2019. Hybrid Breeding of Rice via Genomic Selection. **<ins>Plant Biotechnology Journal**</ins>. (IF: 8.154)](https://onlinelibrary.wiley.com/doi/full/10.1111/pbi.13170)  

**2.** [Kang, K.<sup>#</sup>, Li, J.<sup>#</sup>, **<ins>Li, R.</ins><sup>#</sup>**, Xu, X., Liu, J., Qin, L., Huang, T., Wu, J., Jiao, M., Wei, M., Wang, H., Wang, T., and Zhang, Q., 2019. Potentially critical roles of NDUFB5, TIMMDC1,and VDAC3 in the progression of septic cardiomyopathy through integrated bioinformatics analysis. **<ins>DNA and Cell Biology**</ins>. (IF: 3.191)](https://www.liebertpub.com/doi/10.1089/dna.2019.4859)  

**3.** [Dai, X., Gonzalez, G., Li, L., Li, J., You, C., Miao, W., Hu, J., Fu, L., Zhao, Y., **<ins>Li, R.</ins>**, Li, L., Chen, X.,  Xu, Y., Gu, W., Wang, Y., 2019. YTHDF2 Binds to 5-Methylcytosine in RNA and Modulates the Maturation of Ribosomal RNA. **<ins>Analytical Chemistry**</ins>. (IF: 6.785)](https://pubs.acs.org/doi/abs/10.1021/acs.analchem.9b04505)  

**4.** [Wang, T., Zheng, X., **<ins>Li, R.</ins>**, Liu, X., Wu, J., Zhong, X., Zhang, W., Liu, Y., He, X., Liu, W. and Wang, H., 2019. Integrated bioinformatic analysis reveals YWHAB as a novel diagnostic biomarker for idiopathic pulmonary arterial hypertension. **<ins>Journal of cellular physiology**</ins>, 234(5), pp.6449-6462. (IF: 5.546)](https://doi.org/10.1002/jcp.27381)  

**5.** [Jia, Z., Zhu, J., Zhuo, Y., **<ins>Li, R.</ins>**, Qu, H., Wang, S., Lu, J., Chater, J.M., Ma, R., Liu, Z., and Cai, Z., 2019. Offsetting Expression Profiles of Prognostic Markers in Prostate Tumor versus its Microenvironment. **<ins>Frontiers in Oncology**</ins>, 9, p.539. (IF: 4.848)](https://doi.org/10.3389/fonc.2019.00539)  

**6.** [Wei, J., Xie, W., **<ins>Li, R.</ins>**, Wang, S., Qu, H., Ma, R., Zhou, X. and Jia, Z., 2019. Analysis of trait heritability in functionally partitioned rice genome. **<ins>Heredity**</ins>, pp.1-14. (IF: 3.436)](https://www.nature.com/articles/s41437-019-0244-9)  

**7.** [Wang, S., Wei, J., **<ins>Li, R.</ins>**, Qu, H., Chater, J.M., Ma, R., Li, Y., Xie, W. and Jia, Z., 2019. Identification of optimal prediction models using multi-omic data for selecting hybrid rice. **<ins>Heredity**</ins>, p.1. (IF: 3.436)](https://www.nature.com/articles/s41437-019-0210-6)  

**8.** [Zhou, T., Lin, W., Zhu, Q., Renaud, H., Liu, X., **<ins>Li, R.</ins>**, Tang, C., Ma, C., Rao, T., Tan, Z. and Guo, Y., 2019. The role of PEG3 in the occurrence and prognosis of colon cancer. **<ins>OncoTargets and Therapy**</ins>, 12, pp.6001-6012. (IF: 3.337)](https://doi.org/10.2147/OTT.S208060)  


#### 2018

**1.** [**<ins>Li, R.</ins><sup>#</sup>**, Qu, H.<sup>#</sup>, Wang, S., Wei, J., Zhang, L., Ma, R., Lu, J., Zhu, J., Zhong, W.D. and Jia, Z., 2018. GDCRNATools: an R/Bioconductor package for integrative analysis of lncRNA, miRNA and mRNA data in GDC. **<ins>Bioinformatics**</ins>, 34(14), pp.2515-2517. (IF: 5.610)](https://academic.oup.com/bioinformatics/article/34/14/2515/4917355)  

**2.** [Wei, J., Wang, A., **<ins>Li, R.</ins>**, Qu, H. and Jia, Z., 2018. Metabolome-wide association studies for agronomic traits of rice. **<ins>Heredity**</ins>, 120(4), p.342. (IF: 3.436)](https://www.nature.com/articles/s41437-017-0032-3)  

**3.** [Lu, J., Dong, W., He, H., Han, Z., Zhuo, Y., Mo, R., Liang, Y., Zhu, J., **<ins>Li, R.</ins>**, Qu, H., Zhang, L., Wang, S., Ma, R., Jia, Z. and Zhong, W., 2018. Autophagy induced by overexpression of DCTPP1 promotes tumor progression and predicts poor clinical outcome in prostate cancer. **<ins>International journal of biological macromolecules**</ins>, 118, pp.599-609. (IF: 5.162)](https://doi.org/10.1016/j.ijbiomac.2018.06.005)  

**4.** [Chen, J., **<ins>Li, R.</ins>**, Ferrante, S.P., Wrightsman, T.R., Jia, Z., Burnette, J., Roose, M.L., Wessler, S. and Stajich, J., 2020. Abstract: Resolving the Diploid Genome of Fairchild Mandarin with Single Molecule Sequencing Technologies. **<ins>Plant and Animal Genome XXVI Conference**</ins>.](https://pag.confex.com/pag/xxvi/meetingapp.cgi/Paper/31388) 


#### 2015

**1.** [Gu, W., Gallagher, G.R., Dai, W., Liu, P., **<ins>Li, R.</ins>**, Trombly, M.I., Gammon, D.B., Mello, C.C., Wang, J.P. and Finberg, R.W., 2015. Influenza A virus preferentially snatches noncoding RNA caps. **<ins>Rna**</ins>, 21(12), pp.2067-2075. (IF: 4.320)](https://rnajournal.cshlp.org/content/21/12/2067.full)  
